### PR TITLE
Fix bin2hex util function

### PR DESCRIPTION
**Pull request by pepe**
Add the \0 terminator to resulting buffer.

Add test suite for bin2hex and hex2bin functions.

### CODE REVIEW

**Comment by pepe** [comment]
Fix #1

**Comment by bakpakin** [comment]
This seems to break the identity (deep= x (hex2bin (bin2hex x))). A simpler fix is to just reserve an extra byte in the buffer in the call to janet_buffer_ensure.

Edit: actually changing janet_buffer_ensure to janet_buffer_extra  is also needed

**Comment by bakpakin** [comment]
@pepe I've fixed the bug on master without changing the semantics of bin2hex and hex2bin with code similar to yours. I won't merge this, but thanks for finding the bug and writing a patch.

**Comment by pepe** [comment]
Oh sorry, I have been babysitting yesterday evening. Thank you I will look at your solution.

**Pull request closed without merging**
